export const mockPosts = [
    {
        id: "1",
        title: "Modern Downtown Apartment",
        price: 2500,
        img: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=500",
        address: "123 Main St",
        city: "New York",
        bedroom: 2,
        bathroom: 2,
        type: "rent",
        property: "apartment",
        desc: "Beautiful modern apartment in the heart of downtown with amazing city views.",
        utilities: "included",
        pet: "allowed",
        income: 7500,
        size: 1200,
        school: 8,
        bus: 5,
        restaurant: 10,
        latitude: 40.7128,
        longitude: -74.0060
    },
    {
        id: "2", 
        title: "Luxury Family Home",
        price: 750000,
        img: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=500",
        address: "456 Oak Ave",
        city: "Los Angeles",
        bedroom: 4,
        bathroom: 3,
        type: "buy",
        property: "house",
        desc: "Spacious family home with modern amenities and beautiful garden.",
        utilities: "not included",
        pet: "allowed",
        income: 15000,
        size: 2800,
        school: 9,
        bus: 3,
        restaurant: 7,
        latitude: 34.0522,
        longitude: -118.2437
    },
    {
        id: "3",
        title: "Cozy Studio in City Center",
        price: 1800,
        img: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=500",
        address: "789 Pine St",
        city: "Chicago",
        bedroom: 1,
        bathroom: 1,
        type: "rent",
        property: "apartment",
        desc: "Perfect studio apartment for young professionals in the city center.",
        utilities: "included",
        pet: "not allowed",
        income: 5000,
        size: 600,
        school: 7,
        bus: 2,
        restaurant: 12,
        latitude: 41.8781,
        longitude: -87.6298
    }
];

export const mockUser = {
    id: "1",
    username: "john_doe",
    email: "john@example.com",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150"
}; 