[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-production-api.com/api"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-staging-api.com/api"

[context.branch-deploy.environment]
  VITE_API_URL = "https://your-staging-api.com/api"
